apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voting-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: voting.188.166.206.178.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: voting-app-service
            port:
              number: 80
  - host: db-admin.188.166.206.178.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redis-gui-service
            port:
              number: 80
